### ISSUE TITLE
Files without Exif data aren't handled correctly

### ISSUE THREAD

**Issue by lizmat** [frithnanth/perl6-Image-Libexif#1]
The example programs, and all other code I tried, failed with:
```
Cannot look up attributes in a Image::Libexif::Raw::ExifData type object. Did you forget a '.new'?
  in method ifd at ...site/sources/5CB626BF4325F87DF784D52D1212BBF6717E278F (Image::Libexif::Raw) line 32
  in method info at .../site/sources/8AD5D6371908A829FC5D323173190AD2C75517DC (Image::Libexif) line 173
```
Is there something I'm missing?

**Comment by frithnanth** [comment]
That's odd: line 32 of Image::Libexif::Raw::ExifData is the declaration of a CStruct. The only thing that might seem different from the usual is that that class has an "embedded" attribute declared with `HAS` instead of `has`, but it sounds strange that Linux and MacOS behaved differently on that.

Maybe you have a different version of libexif? Here on a Linux Debian installation I have libexif v0.6.24 and everything works fine.

**Comment by lizmat** [comment]
The version of libexif is the same.

I also tried this on a MacOS with an Intel processor: there it works.  So it appears to be an Apple Silicon related issue  :-(

**Comment by frithnanth** [comment]
A hardware problem? :-o That's very unfortunate!
Might it be a problem related to NativeCall on that specific platform? (not that I'm able to help in that case…)

**Comment by lizmat** [comment]
Possibly: I'll investigate further after the weekly.

Reason for me is to be able to add searching in EXIF information to `App::Rak`.

**Comment by lizmat** [comment]
Before I can add exif searching to `App::Rak`, I would need to add possibly quite a few convenience methods.  Also I noticed that quite a few tagnames are missing, at least from the few files I tried (e.g. 0x0003/04/05/06/10/17/1f).

So my questions: would you prefer me to create a wrapper module (e.g. Image::Info) with Image::Libexif as a dependency.  Or would you rather I add these methods to Image::Libexif itself?

Also: would you consider me taking over support / development of this module?  ( my fingers are itching  :-)

**Comment by frithnanth** [comment]
It works for me both ways, with a slight preference for a wrapper module.
A wrapper module might add features not covered by libexif, add other dependencies, or switch to a different library altogether transparently towards dependent modules.

**Comment by lizmat** [comment]
Ok, I will target an `Image::Info` module then  :-)
